### ISSUE TITLE
How to let it run?

### ISSUE THREAD

**Issue by nerddd** [iwanao731/ofxHairModel#1]
Sorry,I don't know how to config it to let it run successfully.I'm new to CG.Could you please upload the whole project include .sln etc.Thank you very much!

**Comment by iwanao731** [comment]
Hi
Thanks for interesting this repository.
I added a article about how to use this codes in README.md.
Please read it first.
If you still have some question, please ask freely!
Thx!

**Comment by nerddd** [comment]
Oh,you're so kind. I'll have a try. Thank u!~~
