### ISSUE TITLE
Can this run on OS X?

### ISSUE THREAD

**Issue by xiangcong** [iwanao731/ofxHairModel#2]
Hi~Can this run on OS X? 
Thanks！

**Comment by FweiGao** [comment]
Hello，Could you update more detail  README.I get a error  "error	LNK1104	can not open file"tbb_debug.lib”	".May HEmesh or eigen Dependencies have some problems.
THX!

**Comment by iwanao731** [comment]
Unfortunatelly, I've never tried to test with OSX.
