### ISSUE TITLE
Fail to run with VS2019

### ISSUE THREAD

**Issue by MrTornado24** [iwanao731/ofxHairModel#4]
I tried running it with VS2019, but it failed. There are some points that may be confusing to me.

1. I downloaded openFrameworks and import a project from the folder named "example-simpleViewer", with addon "ofxHairModel", "ofxHEMesh" and "ofxRay". 

![image](https://user-images.githubusercontent.com/45503891/176928033-98a45175-7d15-4826-a9ce-6148b34757a0.png)

Did I import a correct folder and correct addons?

2. When I have done the creation of the project, it failed to run with the following errors. I have no idea with the errors, could you give me some tips?

![image](https://user-images.githubusercontent.com/45503891/176929039-37cc309a-34c1-46af-aae7-2ef9023b2a3f.png)

**Comment by iwanao731** [comment]
Hello. Thanks for your comments.
The latest openFrameworks has been dramatically changed math library.
So, this addon may not be worked well for it.
Please use openFrameworks with old version (0.8x series)
